### PR TITLE
ignore xcode files

### PR DESCRIPTION
**Pull request by yuhki50**
not ignore following files.

```
openFrameworks/apps/myApps/mySketch/mySketch.xcodeproj/project.xcworkspace/xcuserdata/
openFrameworks/apps/myApps/mySketch/mySketch.xcodeproj/xcuserdata/
```

### CODE REVIEW

**Comment by r9y9** [comment]
Maybe we should use https://www.gitignore.io/ instead of manually adding these files? The above directories seems to be common in xcode projects, not oF specific ones.

**Comment by r9y9** [comment]
To be clear, I meant that common ignores in xcode projects can be better ignored using gitignore.io rather than manually adding these ignore files.

**Comment by yuhki50** [comment]
I think so. But it's not user friendly. So how do I add all of gitignore that oF support IDEs?
(e.g. https://github.com/openframeworks/openFrameworks/blob/master/.gitignore).

**Comment by r9y9** [comment]
I think this is sensitive problem if we consider various platforms, IDEs, etc. However, if we limit this for osx only for now, I think it's reasonable to consider all of IDE ignores, right? And also, my point was that just "automation is better than manual" :)

**Comment by yuhki50** [comment]
I got it. How about using Yeoman. It's usefull, but needs Nodejs.
https://www.npmjs.com/package/generator-gitignore

**Pull request merged**
